# -----------------------------------------------------
# Pywal Theme Integration
# -----------------------------------------------------
#
include ~/.config/kitty/themes/pywal.conf
# include ~/.config/kitty/themes/Catppuccin-Mocha.conf


# -----------------------------------------------------
# Shaders & Effects 
# -----------------------------------------------------
cursor_trail                  4
# cursor_trail_decay          0.10 0.20


# -----------------------------------------------------
# Shell
# -----------------------------------------------------
shell                       /usr/bin/zsh

# -----------------------------------------------------
# Font
# -----------------------------------------------------
font_family                 JetBrains Mono Nerd Font
bold_font                   JetBrains Mono Nerd Font
font_weight                 bold
italic_font                 auto
bold_italic_font            auto
font_size                   12.0
url_style                   curly
sync_to_monitor             no

# -----------------------------------------------------
# Window
# -----------------------------------------------------
background_opacity          1
window_padding_width        24

# -----------------------------------------------------
# Cursor
# -----------------------------------------------------
cursor_shape                block
cursor_blink_interval       1
cursor_stop_blinking_after  0
confirm_os_window_close     0
allow_remote_control        yes

# -----------------------------------------------------
# Smooth cursor invert / foreground-background match
# -----------------------------------------------------
cursor_text_color           background


# -----------------------------------------------------
#--perf
# -----------------------------------------------------
repaint_delay               8
input_delay                 3

# -----------------------------------------------------
# remote
# -----------------------------------------------------
allow_remote_control        yes


